trigger:
  - main

pool:
  name: COMP367

stages:
# ------------------------------------------------
# Stage 1: Build React Frontend
# ------------------------------------------------
- stage: BuildFrontend
  displayName: 'Build React Frontend'
  jobs:
    - job: BuildReact
      steps:
        - checkout: self

        - task: NodeTool@0
          inputs:
            versionSpec: '18.x'
          displayName: 'Install Node.js'

        - script: |
            npm install
          workingDirectory: graphql-client
          displayName: 'Install frontend dependencies'

        - script: |
            npm run build
          workingDirectory: graphql-client
          displayName: 'Build React frontend'

        - task: PublishBuildArtifacts@1
          inputs:
            pathToPublish: 'graphql-client/dist'
            artifactName: 'react-app'
            publishLocation: 'Container'
          displayName: 'Publish React Artifact'

# ------------------------------------------------
# Stage 2: Build Node.js Backend
# ------------------------------------------------
- stage: BuildBackend
  displayName: 'Build Backend'
  jobs:
    - job: BuildServer
      steps:
        - checkout: self

        - task: NodeTool@0
          inputs:
            versionSpec: '18.x'
          displayName: 'Install Node.js'

        - script: |
            npm install
          workingDirectory: graphql-server
          displayName: 'Install backend dependencies'

        - task: PublishBuildArtifacts@1
          inputs:
            pathToPublish: 'graphql-server'
            artifactName: 'graphql-server'
            publishLocation: 'Container'
          displayName: 'Publish Backend Artifact'

# ------------------------------------------------
# Stage 3: Unit Testing (Mock)
# ------------------------------------------------
- stage: Test
  displayName: 'Run Unit Tests and Coverage'
  jobs:
    - job: TestCode
      steps:
        - checkout: self

        - task: NodeTool@0
          inputs:
            versionSpec: '18.x'

        - script: |
            echo " Running mock unit tests"
            echo "Mock test: All tests passed!" > test.txt
            type test.txt
          workingDirectory: graphql-server
          displayName: 'Mock unit test with coverage output'

# ------------------------------------------------
# Stage 4: Code Analysis (Mock SonarQube)
# ------------------------------------------------
- stage: SonarQube
  displayName: 'Code Analysis (Mocked)'
  condition: succeeded()
  jobs:
    - job: Sonar
      steps:
        - script: echo "SonarQube analysis skipped (mock only)"
          displayName: 'Mock SonarQube Step'

# ------------------------------------------------
# Stage 5: Deliver Artifact
# ------------------------------------------------
- stage: Deliver
  displayName: 'Deliver Artifact'
  jobs:
    - job: Deliver
      steps:
        - script: echo "Delivering artifacts to release pipeline..."
          displayName: 'Deliver Step'

# ------------------------------------------------
# Stage 6: Deploy to Dev
# ------------------------------------------------
- stage: DeployDev
  displayName: 'Deploy to Dev Environment'
  jobs:
    - job: Dev
      steps:
        - script: echo " Deploying to Dev on port 5173"
          displayName: 'Dev Deployment Step'

# ------------------------------------------------
# Stage 7: Deploy to QAT
# ------------------------------------------------
- stage: DeployQAT
  displayName: 'Deploy to QAT Environment'
  jobs:
    - job: QAT
      steps:
        - script: echo "Deploying to QAT Environment"
          displayName: 'QAT Deployment Step'

# ------------------------------------------------
# Stage 8: Deploy to Staging
# ------------------------------------------------
- stage: DeployStaging
  displayName: 'Deploy to Staging Environment'
  jobs:
    - job: Staging
      steps:
        - script: echo "Deploying to Staging Environment"
          displayName: 'Staging Deployment Step'

# ------------------------------------------------
# Stage 9: Deploy to Production
# ------------------------------------------------
- stage: DeployProduction
  displayName: 'Deploy to Production Environment'
  jobs:
    - job: Production
      steps:
        - script: echo "Deploying to Production Environment"
          displayName: 'Production Deployment Step'
