trigger:
  - main

pool:
  name: COMP367

stages:
  # Stage 1: Build Frontend (React + Vite)
  - stage: BuildFrontend
    displayName: 'Build React Frontend'
    jobs:
      - job: BuildReact
        steps:
          - checkout: self

          - task: NodeTool@0
            inputs:
              versionSpec: '18.x'
            displayName: 'Install Node.js'

          - script: |
              npm install
              npm run build
            workingDirectory: graphql-client
            displayName: 'Build React App (Vite)'

          - script: |
              dir graphql-client\dist
            displayName: 'Verify dist folder exists'

          - task: PublishBuildArtifacts@1
            inputs:
              pathToPublish: 'graphql-client/dist'
              artifactName: 'react-app'
              publishLocation: 'Container'
            displayName: 'Publish React Build Artifact'

  # Stage 2: Build Backend (GraphQL Server)
  - stage: BuildBackend
    displayName: 'Install Backend Dependencies'
    jobs:
      - job: InstallBackend
        steps:
          - checkout: self

          - task: NodeTool@0
            inputs:
              versionSpec: '18.x'
            displayName: 'Install Node.js'

          - script: |
              npm install
            workingDirectory: graphql-server
            displayName: 'Install GraphQL Server dependencies'

          - task: PublishBuildArtifacts@1
            inputs:
              pathToPublish: 'graphql-server'
              artifactName: 'graphql-server'
              publishLocation: 'Container'
            displayName: 'Publish GraphQL Server Artifact'
