trigger:
  - main

pool:
  name: COMP367

stages:
  # Stage 1: Build Frontend
  - stage: BuildFrontend
    displayName: 'Build React Frontend'
    jobs:
      - job: BuildReact
        displayName: 'Build React App'
        steps:
          - checkout: self

          - task: NodeTool@0
            inputs:
              versionSpec: '18.x'
            displayName: 'Install Node.js'

          - script: |
              cd frontend
              npm install
              npm run build
              dir build
            displayName: 'Install dependencies and build frontend'

          - task: PublishBuildArtifacts@1
            inputs:
              pathToPublish: 'frontend/build'
              artifactName: 'react-app'
              publishLocation: 'Container'
            displayName: 'Publish Frontend Build'

  # Stage 2: Package Backend
  - stage: BuildBackend
    displayName: 'Package Node.js GraphQL Backend'
    jobs:
      - job: PackageBackend
        displayName: 'Prepare GraphQL Server'
        steps:
          - checkout: self

          - task: NodeTool@0
            inputs:
              versionSpec: '18.x'
            displayName: 'Install Node.js'

          - script: |
              cd backend
              npm install
              echo "Backend dependencies installed."
            displayName: 'Install backend dependencies'

          - task: PublishBuildArtifacts@1
            inputs:
              pathToPublish: 'backend'
              artifactName: 'graphql-server'
              publishLocation: 'Container'
            displayName: 'Publish Backend Code'
