trigger:
  - main

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

stages:
  # Stage 1: Build
  - stage: Build
    displayName: 'Build Application'
    jobs:
      - job: Build
        steps:
          - checkout: self
          - task: NodeTool@0
            inputs:
              versionSpec: '18.x'
            displayName: 'Install Node.js'
          - script: |
              npm install
              npm run build
            displayName: 'Install dependencies & build app'
          - task: PublishBuildArtifacts@1
            inputs:
              pathToPublish: 'build'
              artifactName: 'react-app'
            displayName: 'Publish Frontend Build'

  # Stage 2: Test
  - stage: Test
    displayName: 'Run Tests'
    jobs:
      - job: Test
        steps:
          - script: |
              npm install
              npm test -- --coverage
            displayName: 'Run unit tests with coverage'

  # Stage 3: SonarQube (Optional Integration)
  - stage: SonarQube
    displayName: 'Code Analysis'
    condition: succeeded()
    jobs:
      - job: Sonar
        steps:
          - task: SonarQubePrepare@5
            inputs:
              SonarQube: 'YourSonarServiceConnection'
              scannerMode: 'CLI'
              configMode: 'manual'
              cliProjectKey: 'your-project-key'
              cliProjectName: 'your-project-name'
              cliSources: '.'
          - task: SonarQubeAnalyze@5
          - task: SonarQubePublish@5
            inputs:
              pollingTimeoutSec: '300'

  # Stage 4: Deliver
  - stage: Deliver
    displayName: 'Deliver Artifact'
    jobs:
      - job: Deliver
        steps:
          - script: echo "Delivering artifact to release pipeline..."
            displayName: 'Mock deliver step'

  # Stage 5: Deploy to Dev
  - stage: DeployDev
    displayName: 'Deploy to Dev Environment'
    jobs:
      - job: Dev
        steps:
          - script: echo "Deploying app to Dev environment on port 5000"
            displayName: 'Mock Dev Deployment'

  # Stage 6: Deploy to QAT
  - stage: DeployQAT
    displayName: 'Deploy to QAT Environment'
    jobs:
      - job: QAT
        steps:
          - script: echo "Deploying to QAT environment"
            displayName: 'Mock QAT Deployment'

  # Stage 7: Deploy to Staging
  - stage: DeployStaging
    displayName: 'Deploy to Staging Environment'
    jobs:
      - job: Staging
        steps:
          - script: echo "Deploying to Staging environment"
            displayName: 'Mock Staging Deployment'

  # Stage 8: Deploy to Production
  - stage: DeployProduction
    displayName: 'Deploy to Production Environment'
    jobs:
      - job: Production
        steps:
          - script: echo "Deploying to Production environment"
            displayName: 'Mock Production Deployment'
